Chunking:
  Chunk size: 400
  Overlap: 50

  Savepath: "Datasets\\chunks.json"

Embedding:
  Model: "BAAI/bge-small-en-v1.5"
  Batch: 32

  Savepath: "Datasets\\embeddings.npy"

HNSW:
  Distance Metric: "cosine"
  Max Edges: 16
  EF: 200

  Savepath: "Retrieval\\hnsw_index.bin"