Chunking:
  Chunk size: 400
  Overlap: 50
  Savepath: Datasets\chunks.json
Embedding:
  Batch: 32
  Model: BAAI/bge-small-en-v1.5
  Savepath: Datasets\embeddings.npy
HNSW:
  Distance Metric: cosine
  EF_construct: 200
  EF_search: 60
  Max Edges: 16
  Savepath: Retrieval\hnsw_index.bin
  dim: 384
  number of elements: 48033
  top_k: 3

LLM:
  Model: qwen3:1.7b
  URL: http://localhost:11434/api/generate
  Prompts:
    Default: You are answering a question using knowledge and context. Never mention the context, unless it doesn't have enough infromations, then say so explicitly rather than guessing.
    Reformat: Rewrite the following text as a clean, well-structured encyclopedia-style article. Do not add information that isn't present in the text. Return only the article body with no preamble or commentary.